# Generated by Django 4.2.6 on 2023-12-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
