# Generated by Django 4.2.6 on 2023-12-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_image_book_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='book',
            name='book_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='stroke_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
