# Generated by Django 4.2.6 on 2023-12-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_discount_price_book_book_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
