# Generated by Django 4.2.6 on 2023-12-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='stroke_price',
            new_name='premium_price',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
