# Generated by Django 4.2.6 on 2023-12-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('Sitcom', 'Sitcom'), ('TV Drama Series', 'TV Drama Series'), ('Epic Drama Series', 'Epic Drama Series'), ('TV Talk Show', 'TV Talk Show'), ('Reality Show', 'Reality Show'), ('Documentary', 'Documentary'), ('Comedy', 'Comedy')], max_length=20)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='film_thumbnails/')),
            ],
        ),
    ]
